#!/usr/bin/env python3
"""
Derive Kerr (Boyer-Lindquist) Christoffel symbols symbolically and emit
Rust code for the KerrChristoffels struct + christoffels_at() evaluation.

Output is split into three parts:
  1. Struct definition (fields for each nonzero independent component)
  2. christoffels_at() body (shared subexpressions + field initializers)
  3. geodesic_accel() body (the -Γ^μ_αβ k^α k^β contraction, specialized)

Run:
    python3 derive_kerr_christoffels.py > kerr_generated.txt

Then copy the three blocks into src/math/spacetimes/kerr.rs.

Signature convention: (-,+,+,+). Units G=c=M=1.
Coordinate order: (t, r, theta, phi) = indices (0, 1, 2, 3).
"""

import re

from sympy import (
    symbols, sin, cos, Matrix, diff, simplify, cse, Symbol, Rational,
    rust_code,
)


# 1. Set up coordinates and the Kerr metric in Boyer-Lindquist.
#
# NOTE: deliberately no `real=True` / `nonnegative=True` assumptions here.
# SymPy (<= 1.14) has a bug in rust_code where expressions of the form
# `-x*(y - 1)` are mishandled when y carries any real-implying assumption,
# producing `-x*y - 1` (dropping x from the -1 term). For Kerr BL
# Christoffels specifically, dropping assumptions has no effect on the
# simplified output (verified empirically: identical expressions, identical
# operation counts, no Abs/sqrt/Piecewise leakage).
# 
# Upstream bug: https://github.com/sympy/sympy/issues/29709
t, r, th, ph = symbols('t r theta phi')
a = symbols('a')
coords = [t, r, th, ph]

# Display names (Greek) for comments, identifier names (ASCII) for Rust code.
coord_display = ['t', 'r', 'θ', 'φ']
coord_ident   = ['t', 'r', 'th', 'ph']

Sigma = r**2 + a**2 * cos(th)**2
Delta = r**2 - 2*r + a**2

# Full Kerr BL metric. Only g_tt, g_rr, g_thth, g_phph, g_tphi are nonzero.
g = Matrix.zeros(4, 4)
g[0, 0] = -(1 - 2*r/Sigma)
g[0, 3] = -2*a*r*sin(th)**2 / Sigma
g[3, 0] = g[0, 3]
g[1, 1] = Sigma / Delta
g[2, 2] = Sigma
g[3, 3] = (r**2 + a**2 + 2*a**2*r*sin(th)**2/Sigma) * sin(th)**2

print("# Computing inverse metric...", flush=True)
g_inv = g.inv()


# 2. Compute Christoffel symbols:
#    Γ^μ_{α β} = 1/2 g^{μ σ} ( ∂_α g_{σ β} + ∂_β g_{σ α} - ∂_σ g_{α β} )

def christoffel(mu, alpha, beta):
    s = 0
    for sigma in range(4):
        s += g_inv[mu, sigma] * (
            diff(g[sigma, beta], coords[alpha])
            + diff(g[sigma, alpha], coords[beta])
            - diff(g[alpha, beta], coords[sigma])
        )
    return simplify(s / 2)


print("# Computing Christoffel symbols...", flush=True)

# Collect only independent components (symmetric in lower indices: alpha <= beta)
# and only the nonzero ones.
components = {}  # (mu, alpha, beta) -> expression
for mu in range(4):
    for alpha in range(4):
        for beta in range(alpha, 4):
            expr = christoffel(mu, alpha, beta)
            label = (f"Γ^{coord_display[mu]}_"
                     f"{coord_display[alpha]}{coord_display[beta]}")
            if expr != 0:
                components[(mu, alpha, beta)] = expr
                print(f"#   {label}: nonzero", flush=True)
            else:
                print(f"#   {label}: zero", flush=True)

print(f"# Found {len(components)} nonzero independent components.", flush=True)


# 3. Common subexpression elimination
print("# Running CSE...", flush=True)

keys = list(components.keys())
exprs = [components[k] for k in keys]
replacements, reduced = cse(exprs, optimizations='basic')


# 4. Emit Rust
def field_name(mu, alpha, beta):
    """Rust-safe identifier like 't_tr'."""
    return f"{coord_ident[mu]}_{coord_ident[alpha]}{coord_ident[beta]}"


def field_comment(mu, alpha, beta):
    """Human-readable Christoffel label like 'Γ^θ_φφ'."""
    return (f"Γ^{coord_display[mu]}_"
            f"{coord_display[alpha]}{coord_display[beta]}")


def to_rust(expr):
    """Convert a SymPy expression to Rust source, patching known rough edges."""
    s = rust_code(expr)
    # Replace theta references with our precomputed sin_th/cos_th.
    s = s.replace("theta.sin()", "sin_th")
    s = s.replace("theta.cos()", "cos_th")
    s = s.replace("theta", "th")
    # Rewrite negative powi first: `.powi(-2)` -> `.powi(2).recip()`.
    s = re.sub(r'\.powi\(-(\d+)\)', r'.powi(\1).recip()', s)
    # Protect powi arguments from the integer->float pass below.
    # They must remain i32.
    s = re.sub(r'\.powi\((\d+)\)', r'.powi(\1__KEEP_INT__)', s)
    # Force all bare integer literals to f64.
    s = re.sub(r'(?<![\w.])(\d+)(?![\w.])', r'\1.0', s)
    # Restore the powi arguments.
    s = s.replace('__KEEP_INT__', '')
    return s


print()
print("// " + "="*74)
print("// Generated by tools/derive_kerr_christoffels.py — DO NOT EDIT BY HAND")
print("// " + "="*74)
print()

# ---- Struct definition ----
print("pub struct KerrChristoffels {")
for (mu, alpha, beta) in keys:
    print(f"    {field_name(mu, alpha, beta)}: f64,  "
          f"// {field_comment(mu, alpha, beta)}")
print("}")
print()

# ---- christoffels_at body ----
print("Body of `fn christoffels_at(&self, x: &Vector) -> KerrChristoffels`:")
print()
print("// START AUTOGENERATED VIA christoffel.py")
print("let r = x[1];")
print("let th = x[2];")
print("let a = self.a;")
print("let (sin_th, cos_th) = th.sin_cos();")
print()
for var, expr in replacements:
    print(f"let {var} = {to_rust(expr)};")
print()
print("KerrChristoffels {")
for (mu, alpha, beta), expr in zip(keys, reduced):
    print(f"    // {field_comment(mu, alpha, beta)}")
    print(f"    {field_name(mu, alpha, beta)}: {to_rust(expr)},")
print("}")
print("// END AUTOGENERATED VIA christoffel.py")
print()


# 5. Emit a specialized geodesic_accel contraction
#
# accel^μ = -Σ_{α,β} Γ^μ_{α β} k^α k^β
#
# Using symmetry in (α, β): off-diagonal pairs (α != β) contribute
# 2 * Γ * k^α * k^β, diagonal pairs contribute 1 * Γ * (k^α)^2.

print("Body of `fn geodesic_accel(&self, k: &Vector) -> Vector`:")
print()
print("// START AUTOGENERATED VIA christoffel.py")
print("let [kt, kr, kth, kph] = *k;")
print()

k_names = ['kt', 'kr', 'kth', 'kph']


def accel_component_rust(mu):
    """Build the -sum expression for accel[mu] in Rust."""
    terms = []
    for (m, alpha, beta) in keys:
        if m != mu:
            continue
        field = "self." + field_name(m, alpha, beta)
        if alpha == beta:
            terms.append(f"{field} * {k_names[alpha]} * {k_names[beta]}")
        else:
            # Symmetric pair contributes twice
            terms.append(f"2.0 * {field} * {k_names[alpha]} * {k_names[beta]}")
    if not terms:
        return "0.0"
    return "-(" + "\n        + ".join(terms) + ")"


print("[")
for mu in range(4):
    print(f"    // accel^{coord_display[mu]}")
    print(f"    {accel_component_rust(mu)},")
print("]")
print("// END AUTOGENERATED VIA christoffel.py")