use crate::math::{Vector, christoffel::Christoffels, field::MetricField, metric::TPhiMetric};

#[cfg(test)]
mod tests;

pub struct KerrBoydLindquist {
    a: f64,
}

impl KerrBoydLindquist {
    pub fn new(a: f64) -> KerrBoydLindquist {
        KerrBoydLindquist { a }
    }
}

impl MetricField for KerrBoydLindquist {
    type LocalMetric = TPhiMetric;
    type LocalChristoffels = KerrChristoffels;

    fn metric_at(&self, x: &Vector) -> TPhiMetric {
        let r = x[1];
        let th = x[2];
        let a = self.a;

        // standard boyd-lindquist
        // Σ = r² + a² cos²θ
        // Δ = r² - 2r + a²
        // A = (r² + a²)² - a² Δ sin²θ
        let (sin_th, cos_th) = th.sin_cos();
        let sigma = r * r + a * a * cos_th * cos_th;
        let delta = r * r - 2.0 * r + a * a;
        let alpha = (r * r + a * a).powi(2) - a * a * delta * sin_th * sin_th;

        // g_tt = -(1 - 2r/Σ)
        // g_tφ = -2ar sin²θ / Σ
        // g_rr = Σ/Δ
        // g_θθ = Σ
        // g_φφ = (A/Σ) sin²θ.
        let g_tt = -(1.0 - 2.0 * r / sigma);
        let g_tp = -2.0 * a * r * sin_th * sin_th / sigma;
        let g_rr = sigma / delta;
        let g_thth = sigma;
        let g_pp = (alpha / sigma) * sin_th * sin_th;

        TPhiMetric::new([g_tt, g_rr, g_thth, g_pp, g_tp])
    }

    fn christoffels_at(&self, x: &Vector) -> Self::LocalChristoffels {
        // START AUTOGENERATED VIA christoffel.py
        let r = x[1];
        let th = x[2];
        let a = self.a;
        let (sin_th, cos_th) = th.sin_cos();

        let x0 = r.powi(4);
        let x1 = a.powi(2);
        let x2 = r.powi(2);
        let x3 = x1 * x2;
        let x4 = a.powi(4);
        let x5 = cos_th;
        let x6 = x5.powi(2);
        let x7 = x4 * x6;
        let x8 = x1 * x6;
        let x9 = x2 * x8;
        let x10 = x7 + x9;
        let x11 = x2 + x8;
        let x12 = x11.powi(2);
        let x13 = x12.recip();
        let x14 = 2.0 * r;
        let x15 = x1 + x2;
        let x16 = -x14 + x15;
        let x17 = x16.recip();
        let x18 = x13 * x17;
        let x19 = 2.0 * x2;
        let x20 = 2.0 * th;
        let x21 = x1 * x20.cos() + x1;
        let x22 = x19 + x21;
        let x23 = x22.powi(2).recip();
        let x24 = x20.sin();
        let x25 = x1 * x24;
        let x26 = r * x25;
        let x27 = sin_th;
        let x28 = x27.powi(2);
        let x29 = a * x28;
        let x30 = x11.powi(3).recip();
        let x31 = x16 * x30;
        let x32 = x31 * (-x2 + x8);
        let x33 = x11.recip();
        let x34 = r * x16;
        let x35 = x25 / x22;
        let x36 = -x35;
        let x37 = 2.0 * x3;
        let x38 = x1 * x28;
        let x39 = 8.0 / x22.powi(3);
        let x40 = x14 * x38;
        let x41 = th.tan().recip();
        let x42 = x14 * x41;
        let x43 = r * x4;
        let x44 = (x6 - 1.0).powi(2);
        let x45 = x4 * x44;
        let x46 = x5.powi(3) / x27;

        KerrChristoffels {
            // Γ^t_tr
            t_tr: -x18 * (-x0 + x10 - x3),
            // Γ^t_tθ
            t_tth: -4.0 * x23 * x26,
            // Γ^t_rφ
            t_rph: -x18 * x29 * (3.0 * x0 + x3 - x7 + x9),
            // Γ^t_θφ
            t_thph: a.powi(3) * x13 * x14 * x27.powi(3) * x5,
            // Γ^r_tt
            r_tt: -x32,
            // Γ^r_tφ
            r_tph: x29 * x32,
            // Γ^r_rr
            r_rr: x17 * x33 * (-x11 * (r - 1.0) + x34),
            // Γ^r_rθ
            r_rth: x36,
            // Γ^r_θθ
            r_thth: -x33 * x34,
            // Γ^r_φφ
            r_phph: -x28 * x31 * (r * x12 + x11 * x38 - x28 * x37),
            // Γ^θ_tt
            th_tt: -x26 * x39,
            // Γ^θ_tφ
            th_tph: a * r * x15 * x24 * x39,
            // Γ^θ_rr
            th_rr: x17 * x35,
            // Γ^θ_rθ
            th_rth: r * x33,
            // Γ^θ_θθ
            th_thth: x36,
            // Γ^θ_φφ
            th_phph: -x27 * x30 * x5 * (x11 * (x11 * x15 + x40) + x15 * x40),
            // Γ^φ_tr
            ph_tr: -2.0 * a * x17 * x23 * (-x19 + x21),
            // Γ^φ_tθ
            ph_tth: -a * x13 * x42,
            // Γ^φ_rφ
            ph_rph: -x18
                * (-r.powi(5) - 2.0 * r.powi(3) * x8 + 2.0 * x0 + x10 - x14 * x7 + x3
                    - x4
                    - x43 * x44
                    + x43
                    + x45),
            // Γ^φ_θφ
            ph_thph: x13
                * (x0 * x41 - x1 * x14 * x46 + x1 * x42 + x37 * x46 - x4 * x41
                    + 2.0 * x4 * x46
                    + x41 * x45),
        }
        // END AUTOGENERATED VIA christoffel.py
    }
}

pub struct KerrChristoffels {
    t_tr: f64,    // Γ^t_tr
    t_tth: f64,   // Γ^t_tθ
    t_rph: f64,   // Γ^t_rφ
    t_thph: f64,  // Γ^t_θφ
    r_tt: f64,    // Γ^r_tt
    r_tph: f64,   // Γ^r_tφ
    r_rr: f64,    // Γ^r_rr
    r_rth: f64,   // Γ^r_rθ
    r_thth: f64,  // Γ^r_θθ
    r_phph: f64,  // Γ^r_φφ
    th_tt: f64,   // Γ^θ_tt
    th_tph: f64,  // Γ^θ_tφ
    th_rr: f64,   // Γ^θ_rr
    th_rth: f64,  // Γ^θ_rθ
    th_thth: f64, // Γ^θ_θθ
    th_phph: f64, // Γ^θ_φφ
    ph_tr: f64,   // Γ^φ_tr
    ph_tth: f64,  // Γ^φ_tθ
    ph_rph: f64,  // Γ^φ_rφ
    ph_thph: f64, // Γ^φ_θφ
}

impl Christoffels for KerrChristoffels {
    fn geodesic_accel(&self, k: &Vector) -> Vector {
        // START AUTOGENERATED VIA christoffel.py
        let [kt, kr, kth, kph] = *k;

        [
            // accel^t
            -(2.0 * self.t_tr * kt * kr
                + 2.0 * self.t_tth * kt * kth
                + 2.0 * self.t_rph * kr * kph
                + 2.0 * self.t_thph * kth * kph),
            // accel^r
            -(self.r_tt * kt * kt
                + 2.0 * self.r_tph * kt * kph
                + self.r_rr * kr * kr
                + 2.0 * self.r_rth * kr * kth
                + self.r_thth * kth * kth
                + self.r_phph * kph * kph),
            // accel^θ
            -(self.th_tt * kt * kt
                + 2.0 * self.th_tph * kt * kph
                + self.th_rr * kr * kr
                + 2.0 * self.th_rth * kr * kth
                + self.th_thth * kth * kth
                + self.th_phph * kph * kph),
            // accel^φ
            -(2.0 * self.ph_tr * kt * kr
                + 2.0 * self.ph_tth * kt * kth
                + 2.0 * self.ph_rph * kr * kph
                + 2.0 * self.ph_thph * kth * kph),
        ]
        // END AUTOGENERATED VIA christoffel.py
    }
}
